### ISSUE TITLE
Pressure cal safety

### ISSUE THREAD

**Issue by chrocket** [reilleya/RMTS-Manual#23]
You might want to note to exercise care when releasing the pressure after a pressure cal.   If you crank cal up to 1000 psi (or higher), and open that relief valve, that could pose a danger when that grease cuts loose. Wear safety googles and point away from people.

**Comment by chrocket** [comment]
I didn't appreciate how simple the cal is with the grease gun. With the inner pipes loaded with grease, one handle partial squeeze gets you all the way to PSI. There is no chamber that builds up compressed air.  When you release your arm on the gun, the pressure goes to zero.  So not much of a hazard here, if you pack everything with grease, as per the manual directions.

**Comment by reilleya** [comment]
Yup! I knew grease was the right choice instead of air because it is mostly incompressible and stores very little energy as a result. I'd still make sure to have a paper towel around when opening the valve, but it isn't usually energetic when discharging.
